sonar.projectKey=backend-sigepii
sonar.projectName=backend-sigepii

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.login=

sonar.exclusions=**/node_modules/**, **/dist/**, **/coverage/**